### ISSUE TITLE
all_tests.py won't work with QIIME 1.7.0-dev

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/emperor#215]
Given that the pyqi/qcli transition happened at the beginning of 1.7.0-dev cycle, the script_usage_tests can no longer be imported from qiime.util and running all_tests.py will fail with a `ImportError`.

``` python
Traceback (most recent call last):
  File "all_tests.py", line 13, in <module>
    from qiime.test import run_script_usage_tests
ImportError: cannot import name run_script_usage_tests
```

Hence we have some alternatives:
- Update Emperor to fix this problem and make a new release, then update the docs in QIIME to officially support 0.9.4.
- Update Emperor to fix this problem and make a new release, then update the docs in QIIME to officially support 0.9.4 and also add a way to support older versions of QIIME i. e. 1.7.0.
- Update QIIME to add this function back in qiime/util.
